default_platform(:android)

platform :android do
  desc "Deploy to Firebase"
  lane :deploy do
    begin
      firebase_app_distribution(
        groups: "alpha",
        release_notes:"Bug fixes and improvements",
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
        firebase_cli_path: "/usr/local/bin/firebase",
        firebase_cli_token:"1//0g0O3W2HB8ILWCgYIARAAGBASNwF-L9IrVDO2Sl3xZzDIt5iv8XH_kMJzcFLkIeEC0QwTrKg-dUk0f82jVl6OxLFbrIjre9l9nU8",
        app: "1:1050763890011:android:f5239f6410778886949e7e",
      )
    end
  end
end

